sudo: false

cache:
  directories:
    - $HOME/.sbt

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.12.7

jdk:
  - oraclejdk8

notifications:
  email:
    - nick@nickball.net
